deployment:
  tasks:
    - export DEPLOYPATH=/home2/mydemosi/repositories/villa-web
    - /bin/cp -R * $DEPLOYPATH
    - /usr/local/bin/php /home2/mydemosi/repositories/villa-web/artisan optimize:clear --ansi
    - /usr/local/bin/php /home2/mydemosi/repositories/villa-web/artisan db:seed --class=SocialLinkSeeder --force --ansi